### ISSUE TITLE
你好，请问如何添加右上角的链接？

### ISSUE THREAD

**Issue by wchgeng** [GJXS1980/gjxs.github.io#65]
比如我看到你添加了book。我只知道多了book.html, 请问还有修改什么地方的代码？我想对照着学习下。

万分感谢！

**Comment by GJXS1980** [comment]
> 比如我看到你添加了book。我只知道多了book.html, 请问还有修改什么地方的代码？我想对照着学习下。
> 
> 万分感谢！

<code>book.html</code>前面<ode>-- code--</code>里面的那些命令就是.
