### ISSUE TITLE
关于动态鼠标曲线

### ISSUE THREAD

**Issue by quickprogram** [GJXS1980/gjxs.github.io#67]
动态鼠标曲线颜色太深了，如何改淡一点啊？？

**Comment by JvShaw** [comment]
已经自己解决了

**Comment by caojiele** [comment]
@GJXS1980 请问我的为什么要在layouts/post.html文件和page.html文件中都要添加如下代码：

<script type="text/javascript" src="../../../../js/canvas-nest.min.js"></script>
才能生效？

**Comment by GJXS1980** [comment]
> @GJXS1980 请问我的为什么要在layouts/post.html文件和page.html文件中都要添加如下代码：
> 
> <script type="text/javascript" src="../../../../js/canvas-nest.min.js"></script>
> 才能生效？

相当于在当前页面添加插件才能使用这个功能。
