### ISSUE TITLE
是源码么？如何 部署？

### ISSUE THREAD

**Issue by AndersonHJB** [GJXS1980/gjxs.github.io#68]
后期想部署一个，可以有偿 提供技术支持么？VX：Jiabcdefh

**Comment by GJXS1980** [comment]
> 后期想部署一个，可以有偿 提供技术支持么？VX：Jiabcdefh

是源码，使用部署教程见README文档，部署到云服务器的教程没空写，思路：注册域名、域名备案、购买云服务器、nigx代理、写过脚本一直在拉取github项目更新就像了。
